wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.7
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.10.8
    start_time: 1672351986.561648
    t:
      1:
      - 2
      - 3
      - 12
      - 45
      - 55
      2:
      - 2
      - 3
      - 12
      - 45
      - 55
      3:
      - 23
      4: 3.10.8
      5: 0.13.7
      8:
      - 1
      - 5
